### ISSUE TITLE
About Us: Timeline Fixes

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/AEF-PIC#23]
All fixes made to subsalve should be made here.

- [x] The timeline text should be clickable to change the timeline view
- [x] Timeline Down arrow broken

**Comment by victorjaquez** [comment]
@jtuckertw this is fixed

**Comment by jtuckertw** [comment]
This is not fixed: The timeline text should be clickable to change the timeline view
 Text is still not clickable to change the view.  Currently only the dots work.

![image](https://user-images.githubusercontent.com/45019034/71569537-fe645e00-2a8c-11ea-936e-0137af5225f6.png)

**Comment by jtuckertw** [comment]
Closed this was tested on the new site...
http://aefenvprod.wpengine.com/
